name: Publish to PyPI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/formal-datahub
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract version from tag
        id: extract_version
        run: |
          echo "tag_version=$(echo "${{  github.ref_name }}" | sed 's/^v//')" >> "$GITHUB_OUTPUT"
      - name: Update version in pyproject.toml to ${{ steps.extract_version.outputs.tag_version }}
        run: |
          sed -i "s/^version = \".*\"$/version = \"${{ steps.extract_version.outputs.tag_version }}\"/" pyproject.toml
      - name: Commit version changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bump version to ${{ steps.extract_version.outputs.tag_version }}"
          branch: master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python3 -m
          build
          --sdist
          --wheel
          --outdir ./dist
      - name: Log package files
        run: ls -l ./dist
      - name: Log src files
        run: ls -l ./src
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
